include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = TestDrawing

$(APP_NAME)_OBJC_FILES = $(wildcard *.m)

$(APP_NAME)_MAIN_MODEL_FILE = MainMenu.gorm
$(APP_NAME)_RESOURCE_FILES = MainMenu.gorm

include $(GNUSTEP_MAKEFILES)/application.make

