
include $(GNUSTEP_MAKEFILES)/common.make
PACKAGE_NAME = GFractal
VERSION = 0.1

# The application to be compiled
APP_NAME = GFractal

# The Objective-C source files to be compiled
GFractal_OBJC_FILES = main.m  \
  Controller.m    \
  FractalView.m   \
  FractalWindow.m \


# The Resource files to be copied into the app's resources directory
// GFractal_RESOURCE_FILES = Icons/*

include $(GNUSTEP_MAKEFILES)/application.make

