include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME=NSPanelTest
NSPanelTest_RESOURCE_FILES= \
	icon.tiff \
	Test.strings 

NSPanelTest_RESOURCE_DIRS=
NSPanelTest_OBJC_FILES=\
	NSPanelTest.m \
	NSPanelTest_main.m

ADDITIONAL_LDFLAGS =  #-lefence
ADDITIONAL_INCLUDE_DIRS = 

include $(GNUSTEP_MAKEFILES)/application.make
