include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME = Rhea
BUNDLE_NAME = Rhea
BUNDLE_EXTENSION = .theme
VERSION = 1

Rhea_INSTALL_DIR=$(GNUSTEP_LIBRARY)/Themes
Rhea_PRINCIPAL_CLASS = Rhea

Rhea_OBJC_FILES = \
		Rhea.m

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/bundle.make

-include GNUmakefile.postamble

